name: Preview

on: pull_request

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: DNSControl preview
        id: dns_preview
        uses: ./.github/actions/dnscontrol
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          OUTPUT_FILE: preview.txt
        with:
          args: preview

      - name: Make comment
        uses: unsplash/comment-on-pr@182ec73bcf2b77868dcadd16987721fcfaca76d9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          check_for_duplicate_msg: true
          msg: |
            Preview for ${{ github.event.pull_request.head.sha }}:

            ```text
            ${{ steps.dns_preview.outputs.stdout }}
            ```
